### ISSUE TITLE
dartnissanconnect at rasberry pi >>> Unhandled exception

### ISSUE THREAD

**Issue by Heiner3** [Tobiaswk/dartnissanconnect#4]
Hi Tobias, 
First of all: Thank you for you great work! You seem to me the only one to communicate with Nissan Leafs produced after May 2019. 
After struggling around with pycarwings2 see: [pycarwings2 - v2.13 - INVALID PARAMS #39](https://github.com/filcole/pycarwings2/issues/39)
I installed your dartnissanconnect and I was very glad when the first run showed my nissans battery SOC:
**_Modell:     Leaf
Ladezustand der Batterie: 85.0%_**
But after that it runs **mostly** in ever the same unhadled exception:
```
pi@solaranzeige:~ $ dart /home/pi/dartnissanconnect/example/nissanconnect_soc.dart
null
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("realm")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      NissanConnectSession.login (package:dartnissanconnect/src/nissanconnect_session.dart:191:67)
<asynchronous suspension>
#2      main (file:///home/pi/dartnissanconnect/example/nissanconnect_soc.dart:8:8)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
The same behavior also does your **_nissanconnect_example.dart_**
**Do you have an idea what goes wrong here?**
In any case, your app **_My Leaf_** always runs perfectly...

**Comment by Tobiaswk** [comment]
I cannot reproduce this myself. Can you show me the example you are running?

Den 11. februar 2022 02.20.14 CET, Heiner3 ***@***.***> skrev:
>Hi Tobias, 
>First of all: Thank you for you great work! You seem to me the only one to communicate with Nissan Leafs produced after May 2019. 
>After struggling around with pycarwings2 see: [pycarwings2 - v2.13 - INVALID PARAMS #39](https://github.com/filcole/pycarwings2/issues/39)
>I installed your dartnissanconnect and I was very glad when the first run showed my nissans battery SOC:
>**_Modell:     Leaf
>Ladezustand der Batterie: 85.0%_**
>But after that it runs **mostly** in ever the same unhadled exception:
>```
***@***.***:~ $ dart /home/pi/dartnissanconnect/example/nissanconnect_soc.dart

**Comment by Heiner3** [comment]
My example **_nissanconnect_soc.dart_**:
```
import 'package:dartnissanconnect/dartnissanconnect.dart';
import 'package:intl/intl.dart';

main() {
  NissanConnectSession session = new NissanConnectSession(debug: false);

  session.login(username: "user", password: "passwort").then((vehicle) {
               print("Modell:     ${vehicle.modelName}");
               vehicle.requestBatteryStatus().then((battery) {
               print("Ladezustand der Batterie: ${battery.batteryPercentage}");
    			});
  		});
}
```
and your example **_nissanconnect_example.dart_**:
```
import 'package:dartnissanconnect/dartnissanconnect.dart';

main() {
  NissanConnectSession session = new NissanConnectSession(debug: true);

  session.login(username: "username", password: "password").then((vehicle) {
    print(vehicle.nickname);
    print(vehicle.modelName);
    print(vehicle.vin);
  });
}
```
And as I wrote: Both scripts have the same behavior regarding the unhadled exception

**Comment by Tobiaswk** [comment]
I cannot reproduce your issue.

Are you using the correct library? If your vehicle was produced prior to May 2019 you need to use my other library called dartcarwings.

Den 11. februar 2022 13.30.02 CET, Heiner3 ***@***.***> skrev:

**Comment by Heiner3** [comment]
Hello Tobias,
**_if you would only read this thread from the beginning_**... 
The title is **_dartnissanconnect_** because I own a Nissan Leaf **_produced in 2021_**. 
You don't even think about clicking the two times given link:  [pycarwings2 - v2.13 - INVALID PARAMS #39](https://github.com/filcole/pycarwings2/issues/39)
**And: I wrote it runs**, but not always --> this could not happen with pycarwings in my case!** 
Sorry, in my feeling you do not read what I write at all...

Next I will install **_dartnissanconnect_** on a different Raspberry Pi from scratch and maybe at an old Linux-Notebook.
After that I will report here what happened....

**Comment by Heiner3** [comment]
No luck at all. On all devices it's the same...
